- hosts: all
  become: true
  tasks:
  - name: Apt-get-update
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Install Nginx
    apt:
      name: nginx
      state: present
  - name: Configure Nginx
    copy:
      src: ./files/nginx.conf
      dest: /etc/nginx/sites-available/default
    notify: restart nginx
  - name: Copy netplan config file
    template:
      src: "templates/A/netplan.j2"
      dest: "/etc/netplan/50-vagrant.yaml"
    notify: Apply network configuration

  handlers:
    - name: Apply network configuration
      command: "netplan apply"
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    
